[package]
name = "main-app"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = { version = "1.4.25", features = ["static-msvcrt"] }
internal-lib = { version = "0.1.0", path = "../internal-lib" }
